# Generated by Django 5.2.4 on 2025-08-02 12:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import habits.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Уникальное название места (например: Дом, Офис, Спортзал)",
                        max_length=255,
                        unique=True,
                        verbose_name="Название места",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о месте",
                        null=True,
                        verbose_name="Описание места",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "execution_time",
                    models.TimeField(
                        blank=True, help_text="Введите время выполнения", null=True, verbose_name="Время выполнения"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Конкретное действие, которое представляет привычка",
                        max_length=255,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если привычка приятная",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Интервал в днях между выполнениями (от 1 до 7)",
                        validators=[habits.validators.validate_periodicity],
                        verbose_name="Периодичность в днях",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем пользователь должен себя вознаградить после выполнения (альтернатива связанной привычке)",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_required",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Время в секундах, которое займет выполнение привычки (максимум 120 секунд)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Время на выполнение (секунды)",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте для публикации привычки в общий доступ",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "habit_related",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка, связанная с выполнением этой привычки",
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewarded_habits",
                        to="habits.habit",
                        verbose_name="Связанная приятная привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца привычки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец привычки",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите место выполнения привычки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="habits.place",
                        verbose_name="Место выполнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
